### ISSUE TITLE
how to compile this project with vs IDE?

### ISSUE THREAD

**Issue by zhouxs1023** [cbarbat/eigenmath_pratt#1]
I used vs IDE compile this project,but  turn on error  "cmddisplay()" in run.cpp  file.  can  you  help me ?thank for  your  help

**Comment by cbarbat** [comment]
Look at the Makefile to see how to compile it. When you are using Linux, you can issue the command "make" in the terminal and it compiles. If you use VS IDE, you need to define LINUX, either in some header file or in the compiler command line:

#define LINUX

Then it should compile.

Basically you need to compile each file to an *.obj file and then link them together to an executable math.exe. This is what the Makefile does.

**Comment by zhouxs1023** [comment]
Thank  for your help! need  define  LINUX
